// Even Fibonacci numbers
// website: https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
// N = 4,000,000 -> projecteuler.net
// ANSWER: 4613732
// Constraints:
// 1 <= T <= 10^5
// 10 <= N <= 4 * 10^16

#include <stdio.h>

int main(int argc, char *argv[]) {
	int t;
	scanf("%d", &t);
	while (t--) {
		long int n;
		scanf("%ld", &n);
		long int sum = 0;
		long int fib1 = 1;
		long int fib2 = 2;
		while (fib2 <= n) {
			if (fib2 % 2 == 0) {
				sum += fib2;
			}
			long int temp = fib1;
			fib1 = fib2;
			fib2 = temp + fib1;
		}
		printf("%ld\n", sum);
	}
	return 0;
}